import { Inter, Rozha_One, Poppins, Playfair_Display_SC } from "next/font/google";
import "./globals.css";
import TransitionProvider from "@/components/transitionProvider";

const inter = Inter({
   subsets: ["latin"],
   weight: ["100", "200", "400", "500", "600", "700", "800", "900"],
   });

const rozhaOne = Rozha_One({
   subsets: ["latin"],
   weight: ["400",],
   });
const poppins = Poppins({
   subsets: ["latin"],
   weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
   });
const playfairDisplaySC = Playfair_Display_SC({
   subsets: ["latin"],
   weight: ["400", "700", "900"],
   });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fr">
      
      <body className={`${inter.className} ${rozhaOne.className} ${poppins.className} ${playfairDisplaySC.className} `}>
      <TransitionProvider>{children}</TransitionProvider>
      </body>
    </html>
  );
}
